# list of scenes to download and process
scenes: [
        # # Antarctica - Maitri Station (-70.76683, 11.7308)
        # 'S1B_IW_SLC__1SSH_20190315T195015_20190315T195045_015369_01CC73_DB8B',
        # 'S1B_IW_SLC__1SSH_20190327T195016_20190327T195045_015544_01D236_9504',
        # 'S1B_IW_SLC__1SSH_20190526T195018_20190526T195048_016419_01EE8D_53BC',
        # # Antarctica - Bharati Station (-69.4068, 76.19525)
        # 'S1B_IW_SLC__1SSH_20190223T222639_20190223T222706_015079_01C2E9_1D63',
        # 'S1A_IW_SLC__1SSH_20190605T222724_20190605T222751_027550_031BE1_AD3A',
        # # Antarctica - lutzow-holm bay (-69.6901, 39.4502)
        # 'S1A_IW_SLC__1SSH_20220223T175626_20220223T175653_042043_05021A_BB8E',
        # 'S1A_IW_SLC__1SSH_20221021T175636_20221021T175703_045543_0571D7_989F',
        # # Antarctica - Erebus Ice Tongue (-77.7018, 166.7541) 
        # 'S1A_IW_SLC__1SSH_20190926T124734_20190926T124804_029192_0350B9_FA6B',
        # # Antarctica - Heard, McDonald Island (-53.1057, 73.5431) 
        # 'S1A_IW_SLC__1SSH_20230127T142750_20230127T142817_046970_05A22F_17F7',
        # 'S1A_IW_SLC__1SSH_20230620T142747_20230620T142817_049070_05E69E_0BC7',
        # # Antarctica - Brunt Ice Shelf (-75.216667, -25.683333) 
        # 'S1B_IW_SLC__1SSH_20210223T233056_20210223T233124_025740_031194_E7BE',
        # 'S1B_IW_SLC__1SSH_20210228T035005_20210228T035033_025801_03138F_8CB2',
        # # Antarctica - Victoria Land, East Ross Sea (-72.5, 168) 
        # 'S1A_IW_SLC__1SSH_20230120T160153_20230120T160220_046869_059EC6_F364',
        'S1A_IW_SLC__1SSH_20230116T100627_20230116T100655_046807_059CB3_FCC7',
        # Australia - QLD corner reflector (-27.0252,150.5759)
        # 'S1A_IW_SLC__1SSH_20220104T083315_20220104T083342_041308_04E91B_8E5F',
        # 'S1A_IW_SLC__1SDV_20220111T192213_20220111T192240_041417_04ECBD_9F3B',
        # 'S1A_IW_SLC__1SSH_20220116T083314_20220116T083342_041483_04EED2_DB08',
        # 'S1A_IW_SLC__1SDV_20220123T192213_20220123T192240_041592_04F283_9D0E',
        ]

# we will mount this folder in the docker container so all data can be accessed
# this folder should contain all the downloaded scenes, dems, etc specified below
data_folder: '/data'

#save directory for final opera products
# a sub directory for each scene will be made
pyrosar_output_folder: /data/pyroSAR/outdir

# location of SNAP installation
snap_path: /home/ec2-user/SNAP9/bin #'/Applications/snap/bin' 

# location of earthdata credentials to download data.
# file should be in format shown in credentials_example.txt
earthdata_credentials: credentials_earthdata.txt

# directory to save scenes
scene_folder: /data/scenes

# whether to unzip the safe file
unzip_scene: False

# directory where DEM will be saved - a sub folder is made for each DEM type
dem_folder: /data/dem

# type of dem to download for each scene
# list of valid dems in https://pypi.org/project/dem-stitcher/
dem_type: glo_30

# s3 bucket to push the results
# formatting will be {s3_bucket}/{opera-rtc}/{crs}/{scene}/{product_id}
s3_bucket: deant-data-public-dev

# whether to push to s3
push_to_s3: True

# whether to push the DEM to the S3 bucket
upload_dem: True

# delete files after run
delete_local_files: True

#pyrosar settings - pixel size
pyrosar_spacing: 20

#pyrosar settings - scale of final product
# e.g. linear, db
pyrosar_scaling: linear

# pyrosar settings - reference area
# e.g. gamma0, sigma0, beta0
pyrosar_refarea: gamma0

# pyrosar settings 
# A target geographic reference system in WKT, EPSG, PROJ4 or OPENGIS format.
# See function :func:`spatialist.auxil.crsConvert()` for details.
# e.g. 4326, 3031
# by default set the crs based on the location of the scene on
# the sentinel-2 MGRS grid
#pyrosar_t_srs: default
pyrosar_t_srs: 3031


