name: nrb_env
channels:
  - conda-forge
  - defaults
  - s1-etad
dependencies:
  - python=3.10
  - python-dateutil
  - gdal>=3.5.0
  - click>=7.1.0
  - lxml
  - pip
  - pystac>=1.8.0
  - pystac-client
  - scipy
  - pyroSAR>=0.23.0
  - spatialist>=0.12.0
  - s1etad>=0.5.3
  - s1etad_tools>=0.8.1
  - numpy==1.26.4
  - asf_search
  - pyproj
  - fiona
